Repository Bombardierzy/sozisel, pull requests merged in 2021-12, with the labels that each got.

#190 [Task #186] File size and jitsi config change
  router/app.conf
Labels: bug, frontend

#191 [Fix] Fix urls
  frontend/sozisel-app/src/components/SessionResultScreen/SessionResultRecording/SessionRecordingAnnotatedPlayer/SessionRecordingPublicPlayer.tsx
  frontend/sozisel-app/src/components/utils/Urls/urls.tsx
Labels: bug

#193 [Task #192] Favicon
  backend/sozisel/lib/sozisel_web/schema/resolvers/session_resolvers.ex
  backend/sozisel/lib/sozisel_web/schema/types/session_types.ex
  frontend/sozisel-app/package-lock.json
  frontend/sozisel-app/package.json
  frontend/sozisel-app/public/favicon.ico
  frontend/sozisel-app/src/components/Guards/ParticipantGuard.tsx
  frontend/sozisel-app/src/components/ParticipantActiveSession/Modules/WhiteboardEvent/ParticipantWhiteboardEvent.tsx
  frontend/sozisel-app/src/graphql/queries/session.graphql
  frontend/sozisel-app/webpack.config.js
Labels: frontend
